plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Electric Thought
description: Electric - exciting as if by electric shock, charged with strong emotion.
